/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowUp: typeof import('./src/components/keyviewer/KeyButton/ArrowUp.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ColorInput: typeof import('./src/components/settings/input-components/ColorInput.vue')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    ColorSettings: typeof import('./src/components/settings/sections/ColorSettings.vue')['default']
    ConfigFileSettings: typeof import('./src/components/settings/sections/ConfigFileSettings.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    KeybindInput: typeof import('./src/components/settings/input-components/KeybindInput.vue')['default']
    KeyButton: typeof import('./src/components/keyviewer/KeyButton/KeyButton.vue')['default']
    KeySettings: typeof import('./src/components/settings/sections/KeySettings.vue')['default']
    KeyViewerWebview: typeof import('./src/components/keyviewer/KeyViewerWebview.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    ProgramDescription: typeof import('./src/components/settings/sections/ProgramDescription.vue')['default']
    ResetButton: typeof import('./src/components/settings/input-components/ResetButton.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectInput: typeof import('./src/components/settings/input-components/SelectInput.vue')['default']
    SettingsWebview: typeof import('./src/components/settings/SettingsWebview.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    SliderInput: typeof import('./src/components/settings/input-components/SliderInput.vue')['default']
    StylingSettings: typeof import('./src/components/settings/sections/StylingSettings.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    WindowSettings: typeof import('./src/components/settings/sections/WindowSettings.vue')['default']
  }
}
