/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowUp: typeof import('./src/components/keyviewer/KeyButton/ArrowUp.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    KeyButton: typeof import('./src/components/keyviewer/KeyButton/KeyButton.vue')['default']
    KeyViewerWebview: typeof import('./src/components/keyviewer/KeyViewerWebview.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    SettingsWebview: typeof import('./src/components/settings/SettingsWebview.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    WindowSettings: typeof import('./src/components/settings/sections/WindowSettings.vue')['default']
  }
}
